---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        imagePullPolicy: Always
        image: lgonzalez883/planet_api:1.0
        ports:
        - name: http
          containerPort: 6379
        volumeMounts:
        - name: redis-data-pvc
          mountPath: "/data"
        env:
        - name: REDIS_IP
          value: "redis-service"
        command: ['sh', '-c', 'python3 worker.py']
      volumes:
      - name: redis-data-pvc
        persistentVolumeClaim:
          claimName: redis-data-pvc
