---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-deployment
  labels:
    app: flask-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-api
  template:
    metadata:
      labels:
        app: flask-api
    spec:
      containers:
      - name: flask-api
        imagePullPolicy: Always
        image: lgonzalez883/planet_api:1.0
        ports:
        - name: http
          containerPort: 5000
        volumeMounts:
        - name: redis-data-pvc
          mountPath: "/data"
        env:
        - name: REDIS_IP
          value: "redis-service"
        command: ['sh', '-c', 'python3 flask_api.py']
      volumes:
      - name: redis-data-pvc
        persistentVolumeClaim:
          claimName: redis-data-pvc