---
version: "3"

services:
    redis-db:
        image: redis:7
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        user: "1000:1000"
        command: ["--save", "1", "1"]

    flask-app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        image: lgonzalez883/planet_api:dev
        ports:
            - 5000:5000
        volumes:
            - ./config.yaml:/config.yaml
        environment:
            REDIS_IP: "redis-db"
            REDIS_PORT: "6379"
            LOG_LEVEL: "WARNING"
        command: ["python3", "flask_api.py"]

    worker:
        build:
            context: ./
            dockerfile: ./Dockerfile
        depends_on:
            - redis-db
        image: lgonzalez883/planet_api:dev
        environment:
            REDIS_IP: "redis-db"
            REDIS_PORT: "6379"
            LOG_LEVEL: "WARNING"
        command: ["python3", "worker.py"]
